// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npwcdxrynfuphtxoqxpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wd2NkeHJ5bmZ1cGh0eG9xeHB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMzUxNjEsImV4cCI6MjA2MTkxMTE2MX0.mM-MBxRWqLLD45ww_8vcVoEgScfpUVowDOZL6kCrEtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);